#!/usr/bin/env bash
# install nginx and adjust default homepage
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/defult
sudo ufw allow 'Nginx HTTP'
sudo echo Hello World! > /var/www/html/index.nginx-debian.html
sudo service nginx start
