#!/usr/bin/env bash
# Install Nginx and the init file have only a message
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"
