#!/usr/bin/env bash
# Install Nginx, redirect and 404
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start

sudo service nginx reload

sudo sed -i "s/^\t\}$/\t\}\n\n\terror_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx restart

