#!/usr/bin/env bash
# Configure Nginx server to give error 404 page
apt-get -y update
apt-get -y install nginx

# 3 HTTP 404 error page inclu Ceci n'est pas une page
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/404.html
CUSTOM="error_page 404 /404.html;\nlocation = /404.html {\nroot /var/www/html;\ninternal;\n}"
sudo sed -i "/server_name _;/a $CUSTOM" /etc/nginx/sites-available/default
service nginx restart
