#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

nginx -t
service nginx restart

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null


